# Generated by Django 4.2 on 2023-12-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("pet_num", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Vet",
            fields=[
                ("vet_id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("pet_num", models.IntegerField(default=0)),
                ("clinic_hours", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("pet_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("color", models.CharField(default="", max_length=20)),
                ("months", models.IntegerField()),
                ("years", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[(1, "Dog"), (2, "Cat"), (3, "Bird"), (4, "Fish")],
                        default=1,
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[(1, "Male"), (2, "Female")], default=1, max_length=10
                    ),
                ),
                ("appointments", models.TextField()),
                ("medical_record", models.TextField()),
                ("vaccination", models.TextField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="webApp.client",
                    ),
                ),
                (
                    "vet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pet",
                        to="webApp.vet",
                    ),
                ),
            ],
        ),
    ]
