# Generated by Django 4.2 on 2023-12-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0002_client_user_vet_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="vet",
            name="first_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="vet",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
