# Generated by Django 4.2 on 2023-12-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0004_rename_name_client_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_name",
        ),
    ]
