# Generated by Django 4.2 on 2023-12-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0005_remove_client_first_name_remove_client_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
