# Generated by Django 4.2 on 2023-12-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0006_client_first_name_client_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="vet",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
