# Generated by Django 4.2 on 2023-12-18 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webApp", "0008_remove_client_first_name_remove_client_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="pet_num",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="petowner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="appointments",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="webApp.client",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="color",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="pet",
            name="medical_record",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="months",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="vaccination",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="vet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pet",
                to="webApp.vet",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="years",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="vet",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vet",
            name="clinic_hours",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vet",
            name="pet_num",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="vet",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="vet",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vetuser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
