# Generated by Django 4.2 on 2023-12-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0009_alter_client_address_alter_client_pet_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default=1,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[
                    ("Dog", "Dog"),
                    ("Cat", "Cat"),
                    ("Bird", "Bird"),
                    ("Fish", "Fish"),
                ],
                default=1,
                max_length=10,
            ),
        ),
    ]
