# Generated by Django 4.2 on 2023-12-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0011_item_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/database/"
            ),
        ),
    ]
