# Generated by Django 4.2 on 2023-12-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0013_alter_item_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("Dog", "Dog"),
                    ("Cat", "Cat"),
                    ("Bird", "Bird"),
                    ("Fish", "Fish"),
                ],
                default=1,
                max_length=10,
            ),
        ),
    ]
